# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

services:
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio_minio
      MINIO_DEFAULT_BUCKETS: spark-bucket
    hostname: minio
    ports:
      - 9000
      - 9001:9001

  mysql:
    image: mysql:${MYSQL_VERSION}-oracle
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: metastore
      MYSQL_ALLOW_EMPTY_PASSWORD: TRUE
    hostname: mysql
    ports:
      - 3306
    volumes:
      - ./image/hive-schema-2.3.0.mysql.sql:/docker-entrypoint-initdb.d/hive-schema-2.3.0.mysql.sql
      - ./image/hive-txn-schema-2.3.0.mysql.sql:/docker-entrypoint-initdb.d/hive-txn-schema-2.3.0.mysql.sql

  zookeeper:
    image: zookeeper:${ZOOKEEPER_VERSION}
    ports:
      - 2181
    hostname: zookeeper

  clickhouse-s1r1:
    image: clickhouse/clickhouse-server:${CLICKHOUSE_VERSION}
    hostname: clickhouse-s1r1
    ports:
      - 8123
      - 9000
      - 9100
    volumes:
      - ../clickhouse-core/src/testFixtures/conf/clickhouse-cluster/config.xml:/etc/clickhouse-server/config.xml
      - ../clickhouse-core/src/testFixtures/conf/clickhouse-cluster/remote_servers.xml:/etc/clickhouse-server/config.d/remote_servers.xml
      - ../clickhouse-core/src/testFixtures/conf/clickhouse-cluster/zookeeper.xml:/etc/clickhouse-server/config.d/zookeeper.xml
      - ../clickhouse-core/src/testFixtures/conf/clickhouse-cluster/users.xml:/etc/clickhouse-server/users.xml
      - ../clickhouse-core/src/testFixtures/conf/clickhouse-cluster/s1r1/interserver_http_host.xml:/etc/clickhouse-server/config.d/interserver_http_host.xml
      - ../clickhouse-core/src/testFixtures/conf/clickhouse-cluster/s1r1/macros.xml:/etc/clickhouse-server/config.d/macros.xml
    depends_on:
      - zookeeper

  clickhouse-s1r2:
    image: clickhouse/clickhouse-server:${CLICKHOUSE_VERSION}
    hostname: clickhouse-s1r2
    ports:
      - 8123
      - 9000
      - 9100
    volumes:
      - ../clickhouse-core/src/testFixtures/conf/clickhouse-cluster/config.xml:/etc/clickhouse-server/config.xml
      - ../clickhouse-core/src/testFixtures/conf/clickhouse-cluster/remote_servers.xml:/etc/clickhouse-server/config.d/remote_servers.xml
      - ../clickhouse-core/src/testFixtures/conf/clickhouse-cluster/zookeeper.xml:/etc/clickhouse-server/config.d/zookeeper.xml
      - ../clickhouse-core/src/testFixtures/conf/clickhouse-cluster/users.xml:/etc/clickhouse-server/users.xml
      - ../clickhouse-core/src/testFixtures/conf/clickhouse-cluster/s1r2/interserver_http_host.xml:/etc/clickhouse-server/config.d/interserver_http_host.xml
      - ../clickhouse-core/src/testFixtures/conf/clickhouse-cluster/s1r2/macros.xml:/etc/clickhouse-server/config.d/macros.xml
    depends_on:
      - zookeeper

  clickhouse-s2r1:
    image: clickhouse/clickhouse-server:${CLICKHOUSE_VERSION}
    hostname: clickhouse-s2r1
    ports:
      - 8123
      - 9000
      - 9100
    volumes:
      - ../clickhouse-core/src/testFixtures/conf/clickhouse-cluster/config.xml:/etc/clickhouse-server/config.xml
      - ../clickhouse-core/src/testFixtures/conf/clickhouse-cluster/remote_servers.xml:/etc/clickhouse-server/config.d/remote_servers.xml
      - ../clickhouse-core/src/testFixtures/conf/clickhouse-cluster/zookeeper.xml:/etc/clickhouse-server/config.d/zookeeper.xml
      - ../clickhouse-core/src/testFixtures/conf/clickhouse-cluster/users.xml:/etc/clickhouse-server/users.xml
      - ../clickhouse-core/src/testFixtures/conf/clickhouse-cluster/s2r1/interserver_http_host.xml:/etc/clickhouse-server/config.d/interserver_http_host.xml
      - ../clickhouse-core/src/testFixtures/conf/clickhouse-cluster/s2r1/macros.xml:/etc/clickhouse-server/config.d/macros.xml
    depends_on:
      - zookeeper

  clickhouse-s2r2:
    image: clickhouse/clickhouse-server:${CLICKHOUSE_VERSION}
    hostname: clickhouse-s2r2
    ports:
      - 8123
      - 9000
      - 9100
    volumes:
      - ../clickhouse-core/src/testFixtures/conf/clickhouse-cluster/config.xml:/etc/clickhouse-server/config.xml
      - ../clickhouse-core/src/testFixtures/conf/clickhouse-cluster/remote_servers.xml:/etc/clickhouse-server/config.d/remote_servers.xml
      - ../clickhouse-core/src/testFixtures/conf/clickhouse-cluster/zookeeper.xml:/etc/clickhouse-server/config.d/zookeeper.xml
      - ../clickhouse-core/src/testFixtures/conf/clickhouse-cluster/users.xml:/etc/clickhouse-server/users.xml
      - ../clickhouse-core/src/testFixtures/conf/clickhouse-cluster/s2r2/interserver_http_host.xml:/etc/clickhouse-server/config.d/interserver_http_host.xml
      - ../clickhouse-core/src/testFixtures/conf/clickhouse-cluster/s2r2/macros.xml:/etc/clickhouse-server/config.d/macros.xml
    depends_on:
      - zookeeper

  metastore:
    image: scc-metastore:${PROJECT_VERSION}
    hostname: metastore
    ports:
      - 9083
    volumes:
      - ./image/core-site.xml:/etc/hadoop/conf/core-site.xml
      - ./image/hive-site.xml:/etc/hive/conf/hive-site.xml
    depends_on:
      - mysql

  kyuubi:
    image: scc-kyuubi:${PROJECT_VERSION}
    hostname: kyuubi
    ports:
      - 4040:4040
      - 10009:10009
    volumes:
      - ./image/core-site.xml:/etc/hadoop/conf/core-site.xml
      - ./image/hive-site.xml:/etc/hive/conf/hive-site.xml
      - ./image/spark-defaults.conf:/etc/spark/conf/spark-defaults.conf
      - ./image/kyuubi-defaults.conf:/etc/kyuubi/conf/kyuubi-defaults.conf
      - ../spark-${SPARK_BINARY_VERSION}/clickhouse-spark-runtime/build/libs/clickhouse-spark-runtime-${SPARK_BINARY_VERSION}_${SCALA_BINARY_VERSION}-${PROJECT_VERSION}.jar:/opt/spark/jars/clickhouse-spark-runtime-${SPARK_BINARY_VERSION}_${SCALA_BINARY_VERSION}-${PROJECT_VERSION}.jar
    depends_on:
      - clickhouse-s1r1
      - clickhouse-s1r2
      - clickhouse-s2r1
      - clickhouse-s2r2
      - metastore
      - minio
      - zookeeper
